<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>annotations</Nullable>
        <LangVersion>9</LangVersion>
        <RootNamespace>Wjybxx.Commons.Concurrent</RootNamespace>

        <AssemblyName>Wjybxx.Commons.Concurrent</AssemblyName>
        <PackageId>Wjybxx.Commons.Concurrent</PackageId>
        <PackageVersion>1.3.0</PackageVersion>

        <Title>Wjybxx.Commons.Concurrent</Title>
        <Description>并发基础库；提供事件循环和基于事件循环的await语法</Description>
        <PackageTags>wjybxx;concurrent;eventloop</PackageTags>

        <Authors>wjybxx(845740757@qq.com)</Authors>
        <Owners>wjybxx(845740757@qq.com)</Owners>
        <Copyright>Copyright 2023-2024 wjybxx(845740757@qq.com)</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/hl845740757/commons</PackageProjectUrl>
        <PackageReleaseNotes>https://github.com/hl845740757/commons/releases</PackageReleaseNotes>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <NeutralLanguage>zh-Hans</NeutralLanguage>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <EmbedAllSources>true</EmbedAllSources>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TargetFrameworks>net6.0;net7.0;net8.0;</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <NoWarn>1701;1702;1591;</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <NoWarn>1701;1702;1591;</NoWarn>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Wjybxx.Commons.Core\Wjybxx.Commons.Core.csproj" />
        <ProjectReference Include="..\Wjybxx.Disruptor\Wjybxx.Disruptor.csproj" />
    </ItemGroup>
</Project>