<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>false</ImplicitUsings>
        <Nullable>annotations</Nullable>
        <LangVersion>9</LangVersion>
        <RootNamespace>Wjybxx.Dson.Apt</RootNamespace>

        <AssemblyName>Wjybxx.Dson.Apt</AssemblyName>
        <PackageId>Wjybxx.Dson.Apt</PackageId>
        <PackageVersion>2.4.0</PackageVersion>

        <Title>Wjybxx.Dson.Apt</Title>
        <Description>Dson注解处理器，代码生成工具</Description>
        <PackageTags>wjybxx;dson;json;codec</PackageTags>

        <Authors>wjybxx(845740757@qq.com)</Authors>
        <Owners>wjybxx(845740757@qq.com)</Owners>
        <Copyright>Copyright 2023-2024 wjybxx(845740757@qq.com)</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/hl845740757/commons</PackageProjectUrl>
        <PackageReleaseNotes>https://github.com/hl845740757/commons/releases</PackageReleaseNotes>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <NeutralLanguage>zh-Hans</NeutralLanguage>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <EmbedAllSources>true</EmbedAllSources>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TargetFrameworks>net6.0;net7.0;net8.0;</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <NoWarn>1701;1702;1591;</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <NoWarn>1701;1702;1591;</NoWarn>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Wjybxx.Commons.Apt\Wjybxx.Commons.Apt.csproj" />
        <ProjectReference Include="..\Wjybxx.Dson.Codec\Wjybxx.Dson.Codec.csproj" />
        <ProjectReference Include="..\Wjybxx.Dson.Core\Wjybxx.Dson.Core.csproj" />
    </ItemGroup>
    
</Project>
