<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>annotations</Nullable>
        <LangVersion>9</LangVersion>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Wjybxx.BigCat.Tests</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <NoWarn>1701;1702;1591;0649;NUnit2005;NUnit2006;NUnit2031;NUnit2015</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <NoWarn>1701;1702;1591;0649;NUnit2005;NUnit2006;NUnit2031;NUnit2015</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
        <PackageReference Include="NUnit" Version="3.13.3" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
        <PackageReference Include="NUnit.Analyzers" Version="3.6.1" />

        <ProjectReference Include="..\Wjybxx.BigCat.Core\Wjybxx.BigCat.Core.csproj" />
        <ProjectReference Include="..\Wjybxx.BigCat.Apt\Wjybxx.BigCat.Apt.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <!-- 没研究明白nuget如何设置，暂时和Unity一样通过显式绑定dll启用代码生成 -->
    <ItemGroup>
        <Analyzer Include="../Analyzers/Wjybxx.Commons.Poet.dll" />
        <Analyzer Include="../Analyzers/Wjybxx.Commons.Apt.dll" />
        <Analyzer Include="../Analyzers/Wjybxx.Dson.Apt.dll" />
    </ItemGroup>

    <!-- 排除生成文件目录 -->
    <ItemGroup>
        <None Remove="Generated\**" />
        <Compile Remove="Generated\**" />
        <EmbeddedResource Remove="Generated\**" />
    </ItemGroup>
</Project>
