<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.wjybxx.bigcat</groupId>
    <artifactId>bigcat-framework</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>Framework</name>
    <description>game tools and framework</description>
    <url>https://github.com/hl845740757/BigCat</url>

    <modules>
        <module>core</module>
        <module>reload</module>
        <module>testout</module>
    </modules>

    <!-- 证书 -->
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <!-- 供应者信息 -->
    <scm>
        <url>https://github.com/hl845740757/BigCat</url>
        <connection>scm:git:https://github.com/hl845740757/BigCat.git</connection>
        <developerConnection>https://github.com/hl845740757</developerConnection>
    </scm>
    <!-- issue -->
    <issueManagement>
        <system>Github Issue</system>
        <url>https://github.com/hl845740757/BigCat/issues</url>
    </issueManagement>
    <!-- 开发者信息 -->
    <developers>
        <developer>
            <name>wjybxx</name>
            <email>845740757@qq.com</email>
            <url>https://github.com/hl845740757</url>
            <timezone>+8</timezone>
        </developer>
    </developers>

    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <!-- mvn命令默认gbk编码导致中文注释异常，需要通过这里设置 -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>utf-8</project.reporting.outputEncoding>

        <!-- 基础依赖 -->
        <slf4j.version>2.0.17</slf4j.version>
        <logback.version>1.5.17</logback.version>
        <junit.version>5.12.0</junit.version>
        <!-- 我的commons库 -->
        <commons.version>1.6.0</commons.version>
        <!-- 基础工具库 -->
        <fastutil.version>8.5.14</fastutil.version>
        <commons-lang3.version>3.17.0</commons-lang3.version>
        <commons-io.version>2.18.0</commons-io.version>
        <commons-codec.version>1.18.0</commons-codec.version>
        <guava.version>33.4.0-jre</guava.version>
        <guice.version>7.0.0</guice.version>

        <!-- 特殊依赖 -->
        <netty.version>4.1.119.Final</netty.version>
        <bson.version>4.11.5</bson.version>
        <pb.version>3.25.6</pb.version> <!-- 4.26尚不稳定 -->
    </properties>

    <dependencies>
        <!-- 全局依赖 -->
        <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/ch.qos.logback/logback-classic -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>3.0.2</version>
            <scope>compile</scope>
        </dependency>

        <!-- commons -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>${commons-codec.version}</version>
        </dependency>
        <!-- wjybxx-commons -->
        <dependency>
            <groupId>cn.wjybxx.commons</groupId>
            <artifactId>commons-base</artifactId>
            <version>${commons.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.wjybxx.commons</groupId>
            <artifactId>commons-concurrent</artifactId>
            <version>${commons.version}</version>
        </dependency>

        <!-- 序列化 -->
        <dependency>
            <groupId>cn.wjybxx.commons</groupId>
            <artifactId>dson-core</artifactId>
            <version>${commons.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.wjybxx.commons</groupId>
            <artifactId>dson-codec</artifactId>
            <version>${commons.version}</version>
        </dependency>

        <!-- 行为树 -->
        <dependency>
            <groupId>cn.wjybxx.commons</groupId>
            <artifactId>btree-core</artifactId>
            <version>${commons.version}</version>
        </dependency>
        <!-- 行为树 -->
        <dependency>
            <groupId>cn.wjybxx.commons</groupId>
            <artifactId>btree-codec</artifactId>
            <version>${commons.version}</version>
        </dependency>

        <!-- 依赖注入 -->
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>${guice.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- protobuf -->
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>${pb.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- 升级guava依赖 -->
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>

        <!-- netty, transport会引入所有基础模块 -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>${netty.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- 模块版本同步 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.5.0</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>oss</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- 指定参数-parameters，否则test目录下文件编译异常 -->
            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <encoding>UTF8</encoding>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <!-- 注解处理器的依赖 -->
                        <dependency>
                            <groupId>com.google.code.findbugs</groupId>
                            <artifactId>jsr305</artifactId>
                            <version>3.0.2</version>
                        </dependency>
                        <dependency>
                            <groupId>com.squareup</groupId>
                            <artifactId>javapoet</artifactId>
                            <version>1.13.0</version>
                        </dependency>
                        <dependency>
                            <groupId>cn.wjybxx.commons</groupId>
                            <artifactId>commons-apt-base</artifactId>
                            <version>${commons.version}</version>
                        </dependency>
                        <!-- 注解处理器 -->
                        <annotationProcessorPath>
                            <groupId>com.google.auto.service</groupId>
                            <artifactId>auto-service</artifactId>
                            <version>1.1.1</version>
                        </annotationProcessorPath>
                        <annotationProcessorPath>
                            <groupId>cn.wjybxx.commons</groupId>
                            <artifactId>dson-apt</artifactId>
                            <version>${commons.version}</version>
                        </annotationProcessorPath>
                        <annotationProcessorPath>
                            <groupId>cn.wjybxx.bigcat</groupId>
                            <artifactId>bigcat-apt</artifactId>
                            <version>${project.version}</version>
                        </annotationProcessorPath>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <!-- 源码插件 -->
            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-source-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <!-- 以下操作较为耗时，仅在release模式下执行 -->
        <profile>
            <id>release</id>
            <!-- 发布管理，id与mvn setting.xml 中的 server 对应 -->
            <distributionManagement>
                <snapshotRepository>
                    <id>sonatype-oss</id>
                    <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
                </snapshotRepository>
                <repository>
                    <id>sonatype-oss</id>
                    <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
                </repository>
            </distributionManagement>
            <build>
                <plugins>
                    <!-- 文档插件 -->
                    <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-javadoc-plugin -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>3.5.0</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <!-- 注释不是特别规范，避免打包中断 -->
                                <configuration>
                                    <doclint>none</doclint>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                    <!-- gpg签名插件 -->
                    <plugin>
                        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-gpg-plugin -->
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <!-- id与mvn setting.xml的 gpg 配置中的 id 对应-->
                                <id>ossrh</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- maven部署相关插件 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-deploy-plugin</artifactId>
                        <version>3.1.0</version>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.plugins</groupId>
                        <artifactId>nexus-staging-maven-plugin</artifactId>
                        <version>1.6.13</version>
                        <extensions>true</extensions>
                        <configuration>
                            <!-- serverId与mvn setting.xml 中的 server 对应-->
                            <!-- 该插件用于自动close并release仓库，不使用插件则需要登录网页手动操作 -->
                            <serverId>sonatype-oss</serverId>
                            <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
                            <autoReleaseAfterClose>true</autoReleaseAfterClose>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>