<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>annotations</Nullable>
        <LangVersion>9</LangVersion>
        <RootNamespace>Wjybxx.Disruptor</RootNamespace>

        <AssemblyName>Wjybxx.Disruptor</AssemblyName>
        <PackageId>Wjybxx.Disruptor</PackageId>
        <PackageVersion>1.2.0</PackageVersion>

        <Title>Wjybxx.Disruptpr</Title>
        <Description>LMAX-Disruptor的C#精简实现，保留其核心设计，更好的抽象和扩展性</Description>
        <PackageTags>wjybxx;concurrent;disruptor</PackageTags>

        <Authors>wjybxx(845740757@qq.com)</Authors>
        <Copyright>Copyright 2023-2024 wjybxx(845740757@qq.com)</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/hl845740757/commons</PackageProjectUrl>
        <PackageReleaseNotes>https://github.com/hl845740757/commons/releases</PackageReleaseNotes>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <NeutralLanguage>zh-Hans</NeutralLanguage>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <EmbedAllSources>true</EmbedAllSources>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TargetFrameworks>net6.0;net7.0;net8.0;</TargetFrameworks>
    </PropertyGroup>
    
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <NoWarn>1701;1702;1591;</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <NoWarn>1701;1702;1591;</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
