<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>annotations</Nullable>
        <LangVersion>9</LangVersion> <!-- 为兼容unity我们使用c#9 -->
        <RootNamespace>Wjybxx.BigCatEditor.Protobuf</RootNamespace>

        <AssemblyName>Wjybxx.BigCatEditor.Protobuf</AssemblyName>
        <PackageId>Wjybxx.BigCatEditor.Protobuf</PackageId>
        <PackageVersion>1.0.0</PackageVersion>

        <Title>Wjybxx.BigCatEditor.Protobuf</Title>
        <Description>Protobuf工具包，将pb文件解析为内存结构，用于代码生成等</Description>
        <PackageTags>wjybxx;bigcat;</PackageTags>

        <Authors>wjybxx(845740757@qq.com)</Authors>
        <Owners>wjybxx(845740757@qq.com)</Owners>
        <Copyright>Copyright 2023-2024 wjybxx(845740757@qq.com)</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/hl845740757/BigCat</PackageProjectUrl>
        <PackageReleaseNotes>https://github.com/hl845740757/BigCat/releases</PackageReleaseNotes>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <NeutralLanguage>zh-Hans</NeutralLanguage>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <EmbedAllSources>true</EmbedAllSources> <!-- 嵌入源代码 -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TargetFrameworks>net6.0;net7.0;net8.0;</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <NoWarn>1701;1702;1591;8632;0419</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <NoWarn>1701;1702;1591;8632;0419</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Wjybxx.BigCatEditor.Core\Wjybxx.BigCatEditor.Core.csproj" />
    </ItemGroup>

</Project>
