<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>annotations</Nullable>
        <LangVersion>9</LangVersion> <!-- 为兼容unity我们使用c#9 -->
        <RootNamespace>Wjybxx.BigCat</RootNamespace>

        <AssemblyName>Wjybxx.BigCat.Core</AssemblyName>
        <PackageId>Wjybxx.BigCat.Core</PackageId>
        <PackageVersion>1.0.0</PackageVersion>

        <Title>Wjybxx.BigCat.Core</Title>
        <Description>BigCat核心包</Description>
        <PackageTags>wjybxx;bigcat;</PackageTags>

        <Authors>wjybxx(845740757@qq.com)</Authors>
        <Owners>wjybxx(845740757@qq.com)</Owners>
        <Copyright>Copyright 2023-2024 wjybxx(845740757@qq.com)</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/hl845740757/BigCat</PackageProjectUrl>
        <PackageReleaseNotes>https://github.com/hl845740757/BigCat/releases</PackageReleaseNotes>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <NeutralLanguage>zh-Hans</NeutralLanguage>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <EmbedAllSources>true</EmbedAllSources> <!-- 嵌入源代码 -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TargetFrameworks>net6.0;net8.0;</TargetFrameworks>
        
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <NoWarn>1701;1702;1591;8632;0419</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <NoWarn>1701;1702;1591;8632;0419</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <!-- OutputItemType="Analyzer" 表示将项目添加为分析器，ReferenceOutputAssembly="false" 表示此项目无需拷贝到当前程序集输出目录 -->
    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.31.0" />
        <PackageReference Include="Wjybxx.Commons.Concurrent" Version="1.5.0-rc1" />
        <PackageReference Include="Wjybxx.Commons.Core" Version="1.5.0-rc2" />
        <PackageReference Include="Wjybxx.Commons.Inject" Version="1.5.0-rc1" />
        <PackageReference Include="Wjybxx.Disruptor" Version="1.2.0" />
        <PackageReference Include="Wjybxx.Dson.Core" Version="2.5.4" />
        <PackageReference Include="Wjybxx.Dson.Codec" Version="2.5.4" />

        <ProjectReference Include="..\Wjybxx.BigCat.Apt\Wjybxx.BigCat.Apt.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <!-- 没研究明白nuget如何设置，暂时和Unity一样通过显式绑定dll启用代码生成 -->
    <ItemGroup>
        <Analyzer Include="../Analyzers/Wjybxx.Commons.Poet.dll" />
        <Analyzer Include="../Analyzers/Wjybxx.Commons.Apt.dll" />
        <Analyzer Include="../Analyzers/Wjybxx.Dson.Apt.dll" />
    </ItemGroup>
    <!-- 排除生成文件目录 -->
    <ItemGroup>
        <None Remove="Generated\**" />
        <Compile Remove="Generated\**" />
        <EmbeddedResource Remove="Generated\**" />
    </ItemGroup>
</Project>
